# Generated by Django 5.2.9 on 2026-02-02 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import wine_cellar.apps.household.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Household Name"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
            ],
            options={
                "verbose_name": "Household",
                "verbose_name_plural": "Households",
            },
        ),
        migrations.CreateModel(
            name="HouseholdSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en-gb", "British English")],
                        default="en-gb",
                        max_length=7,
                        verbose_name="Language",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro"),
                            ("USD", "Dollar"),
                            ("GBP", "Pound Sterling"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "notifications",
                    models.BooleanField(default=True, verbose_name="Notifications"),
                ),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
            ],
            options={
                "verbose_name": "Household Settings",
                "verbose_name_plural": "Household Settings",
            },
        ),
        migrations.CreateModel(
            name="HouseholdInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("VI", "Viewer"),
                            ("ME", "Member"),
                            ("AD", "Admin"),
                            ("OW", "Owner"),
                        ],
                        default="ME",
                        max_length=2,
                        verbose_name="Role",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=wine_cellar.apps.household.models.generate_invitation_token,  # noqa: E501
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("AC", "Accepted"),
                            ("DE", "Declined"),
                            ("EX", "Expired"),
                        ],
                        default="PE",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "expires",
                    models.DateTimeField(
                        default=wine_cellar.apps.household.models.get_invitation_expiry,
                        verbose_name="Expires",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="household_invitations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Household Invitation",
                "verbose_name_plural": "Household Invitations",
                "indexes": [
                    models.Index(fields=["token"], name="invitation_token_idx"),
                    models.Index(
                        fields=["email", "status"], name="invitation_email_status_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HouseholdMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("VI", "Viewer"),
                            ("ME", "Member"),
                            ("AD", "Admin"),
                            ("OW", "Owner"),
                        ],
                        default="ME",
                        max_length=2,
                        verbose_name="Role",
                    ),
                ),
                (
                    "joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Joined"),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Household Membership",
                "verbose_name_plural": "Household Memberships",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "household"), name="unique_household_membership"
                    )
                ],
            },
        ),
    ]
