# Generated by Django 5.2.9 on 2026-02-02 17:38

from django.db import migrations


def create_households_for_existing_users(apps, schema_editor):
    """Create a default household for each existing user."""
    User = apps.get_model("auth", "User")
    Household = apps.get_model("household", "Household")
    HouseholdMembership = apps.get_model("household", "HouseholdMembership")
    HouseholdSettings = apps.get_model("household", "HouseholdSettings")
    UserSettings = apps.get_model("user", "UserSettings")

    for user in User.objects.all():
        # Create a household for this user
        household = Household.objects.create(name=f"{user.username}'s Cellar")

        # Create owner membership
        HouseholdMembership.objects.create(
            user=user,
            household=household,
            role="OW",  # Owner
        )

        # Create household settings, copying from user settings if available
        try:
            user_settings = UserSettings.objects.get(user=user)
            HouseholdSettings.objects.create(
                household=household,
                language=user_settings.language,
                currency=user_settings.currency,
                notifications=user_settings.notifications,
            )
            # Set active household
            user_settings.active_household = household
            user_settings.save()
        except UserSettings.DoesNotExist:
            # Create default household settings
            HouseholdSettings.objects.create(
                household=household,
            )


def reverse_migration(apps, schema_editor):
    """Reverse: delete all households (use with caution!)."""
    Household = apps.get_model("household", "Household")
    Household.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0001_create_household_models"),
        ("user", "0006_add_active_household"),
    ]

    operations = [
        migrations.RunPython(
            create_households_for_existing_users,
            reverse_migration,
        ),
    ]
