# Generated by Django 6.0.3 on 2026-03-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0002_populate_existing_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="householdsettings",
            name="language",
        ),
    ]
