# Generated by Django 5.2.9 on 2026-01-19 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0009_storageitem_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Device Name")),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique identifier for the device",
                        max_length=100,
                        unique=True,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="API Token"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Seen"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Firmware Version",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hardware_devices",
                        to="storage.storage",
                        verbose_name="Assigned Storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hardware Device",
                "verbose_name_plural": "Hardware Devices",
            },
        ),
        migrations.CreateModel(
            name="OfflineOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "operation_type",
                    models.CharField(max_length=50, verbose_name="Operation Type"),
                ),
                ("operation_data", models.JSONField(verbose_name="Operation Data")),
                (
                    "client_timestamp",
                    models.DateTimeField(
                        help_text="When the operation was performed on the device",
                        verbose_name="Client Timestamp",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Synced At"),
                ),
                ("applied", models.BooleanField(default=False, verbose_name="Applied")),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_operations",
                        to="hardware.hardwaredevice",
                        verbose_name="Device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Operation",
                "verbose_name_plural": "Offline Operations",
                "ordering": ["client_timestamp"],
            },
        ),
    ]
