# Generated by Django 5.2.9 on 2026-01-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_initial"),
        ("storage", "0009_storageitem_rating"),
        ("wine", "0026_alter_drinkrecord_rating_alter_wine_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionChangeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "row",
                    models.IntegerField(
                        blank=True,
                        help_text="Row detected by vision system, -1 if unknown",
                        null=True,
                        verbose_name="Detected Row",
                    ),
                ),
                (
                    "column",
                    models.IntegerField(
                        blank=True,
                        help_text="Column detected by vision system, -1 if unknown",
                        null=True,
                        verbose_name="Detected Column",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("added", "Bottle Added"),
                            ("removed", "Bottle Removed"),
                            ("reconciliation", "Reconciliation Discrepancy"),
                        ],
                        max_length=20,
                        verbose_name="Change Type",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score from 0.0 to 1.0",
                        verbose_name="Detection Confidence",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hardware/position_changes/%Y/%m/",
                        verbose_name="Snapshot Image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("auto_applied", "Auto-Applied"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Review Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "final_row",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Confirmed Row"
                    ),
                ),
                (
                    "final_column",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Confirmed Column"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_reviews",
                        to="storage.storage",
                        verbose_name="Storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position_reviews",
                        to="wine.wine",
                        verbose_name="Wine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position Change Review",
                "verbose_name_plural": "Position Change Reviews",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RackSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="hardware/snapshots/%Y/%m/%d/",
                        verbose_name="Snapshot Image",
                    ),
                ),
                (
                    "grid_state",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of detected bottle positions",
                        null=True,
                        verbose_name="Grid State",
                    ),
                ),
                (
                    "discrepancies",
                    models.JSONField(
                        blank=True,
                        help_text="Differences between detected and database state",
                        null=True,
                        verbose_name="Discrepancies",
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(default=False, verbose_name="Reconciled"),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="storage.storage",
                        verbose_name="Storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rack Snapshot",
                "verbose_name_plural": "Rack Snapshots",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RackVisionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "auto_apply_threshold",
                    models.IntegerField(
                        default=90,
                        help_text=(
                            "Confidence threshold (0-100) for "
                            "auto-applying detections"
                        ),
                        verbose_name="Auto-Apply Threshold",
                    ),
                ),
                (
                    "enable_hourly_snapshots",
                    models.BooleanField(
                        default=True, verbose_name="Enable Hourly Snapshots"
                    ),
                ),
                (
                    "enable_daily_reconciliation",
                    models.BooleanField(
                        default=True, verbose_name="Enable Daily Reconciliation"
                    ),
                ),
                (
                    "is_calibrated",
                    models.BooleanField(default=False, verbose_name="Calibrated"),
                ),
                (
                    "calibrated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Calibrated At"
                    ),
                ),
                (
                    "calibration_data",
                    models.JSONField(
                        blank=True,
                        help_text="Corner points and perspective transform data",
                        null=True,
                        verbose_name="Calibration Data",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        help_text="The storage rack monitored by the Pi camera",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vision_config",
                        to="storage.storage",
                        verbose_name="Vision-Enabled Storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rack Vision Configuration",
                "verbose_name_plural": "Rack Vision Configurations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user",), name="unique_vision_config_per_user"
                    )
                ],
            },
        ),
    ]
