# Generated by Django 5.2.9 on 2026-02-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_positionchangereview_racksnapshot_rackvisionconfig"),
        ("household", "0002_populate_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwaredevice",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="household.household",
                verbose_name="Household",
            ),
        ),
        migrations.AddField(
            model_name="offlineoperation",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="household.household",
                verbose_name="Household",
            ),
        ),
        migrations.AddField(
            model_name="positionchangereview",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="household.household",
                verbose_name="Household",
            ),
        ),
        migrations.AddField(
            model_name="racksnapshot",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="household.household",
                verbose_name="Household",
            ),
        ),
        migrations.AddField(
            model_name="rackvisionconfig",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="household.household",
                verbose_name="Household",
            ),
        ),
    ]
