# Generated by Django 5.2.9 on 2026-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_rackvisionconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardwaredevice",
            name="device_id",
            field=models.CharField(
                help_text="Unique identifier for the device",
                max_length=100,
                unique=True,
                verbose_name="Device ID",
            ),
        ),
    ]
