# Generated by Django 5.2.9 on 2025-12-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0016_alter_attribute_options_alter_foodpairing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="subregion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Subregion"
            ),
        ),
    ]
