# Generated by Django 5.2.9 on 2025-12-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0017_wine_subregion"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="rrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="RRP",
            ),
        ),
    ]
