# Generated by Django 5.2.9 on 2025-12-31 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0019_bottlenote_drinkingwindowalert_drinkrecord_wishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReorderReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Minimum Stock"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wine.wine",
                        verbose_name="Wine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reorder Reminder",
                "verbose_name_plural": "Reorder Reminders",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wine", "user"), name="unique_reorder_reminder"
                    )
                ],
            },
        ),
    ]
