# Generated by Django 5.2.9 on 2026-01-04 17:01

from django.db import migrations, models


# Mapping from numeric liters to size codes
SIZE_LITERS_TO_CODE = {
    0.1875: "PI",
    0.375: "DE",
    0.5: "HA",
    0.75: "ST",
    1.0: "LI",
    1.5: "MA",
    3.0: "JE",
    4.5: "RE",
}


def convert_sizes_forward(apps, schema_editor):
    """Convert existing float sizes to choice codes."""
    Size = apps.get_model("wine", "Size")
    for size in Size.objects.all():
        # Find the matching code for this numeric size
        code = SIZE_LITERS_TO_CODE.get(size.name_float, "ST")
        size.name = code
        size.save()


def convert_sizes_backward(apps, schema_editor):
    """Reverse: convert codes back to float sizes."""
    CODE_TO_LITERS = {v: k for k, v in SIZE_LITERS_TO_CODE.items()}
    Size = apps.get_model("wine", "Size")
    for size in Size.objects.all():
        size.name_float = CODE_TO_LITERS.get(size.name, 0.75)
        size.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0020_reorderreminder"),
    ]

    operations = [
        # Step 1: Remove the unique constraint that references 'name'
        migrations.RemoveConstraint(
            model_name="size",
            name="unique size",
        ),
        # Step 2: Rename old name field to name_float
        migrations.RenameField(
            model_name="size",
            old_name="name",
            new_name="name_float",
        ),
        # Step 3: Add new name field as CharField
        migrations.AddField(
            model_name="size",
            name="name",
            field=models.CharField(
                choices=[
                    ("PI", "Piccolo (187ml)"),
                    ("DE", "Demi (375ml)"),
                    ("HA", "Half (500ml)"),
                    ("ST", "Standard (750ml)"),
                    ("LI", "Liter (1L)"),
                    ("MA", "Magnum (1.5L)"),
                    ("JE", "Jeroboam (3L)"),
                    ("RE", "Rehoboam (4.5L)"),
                ],
                default="ST",
                max_length=2,
                verbose_name="Size",
            ),
        ),
        # Step 4: Run data migration to populate codes
        migrations.RunPython(convert_sizes_forward, convert_sizes_backward),
        # Step 5: Remove the old float field
        migrations.RemoveField(
            model_name="size",
            name="name_float",
        ),
        # Step 6: Add back the unique constraint
        migrations.AddConstraint(
            model_name="size",
            constraint=models.UniqueConstraint(
                fields=["name", "user"],
                name="unique size",
            ),
        ),
    ]
