# Generated by Django 5.2.9 on 2026-01-11 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0021_convert_size_to_named_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wine",
            index=models.Index(fields=["user", "wine_type"], name="wine_user_type_idx"),
        ),
        migrations.AddIndex(
            model_name="wine",
            index=models.Index(fields=["name"], name="wine_name_idx"),
        ),
        migrations.AddIndex(
            model_name="wine",
            index=models.Index(fields=["barcode"], name="wine_barcode_idx"),
        ),
    ]
