# Generated by Django 5.2.9 on 2026-01-11 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0022_add_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="drinkrecord",
            index=models.Index(
                fields=["user", "date_consumed"], name="drinkrecord_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wine",
            index=models.Index(
                fields=["user", "vintage"], name="wine_user_vintage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wine",
            index=models.Index(
                fields=["user", "drink_by"], name="wine_user_drinkby_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wine",
            index=models.Index(
                fields=["user", "created"], name="wine_user_created_idx"
            ),
        ),
    ]
