# Generated by Django 5.2.9 on 2026-01-15 13:27

from django.conf import settings
from django.db import migrations, models


def migrate_drink_by_to_window(apps, schema_editor):
    """Convert drink_by dates to drink_from/drink_to years."""
    Wine = apps.get_model("wine", "Wine")
    for wine in Wine.objects.filter(drink_by__isnull=False):
        drink_to_year = wine.drink_by.year
        # Set drink_from to 3 years before drink_to (matching old logic)
        drink_from_year = drink_to_year - 3
        wine.drink_to = drink_to_year
        wine.drink_from = drink_from_year
        wine.save(update_fields=["drink_from", "drink_to"])


def reverse_migration(apps, schema_editor):
    """Reverse: clear the new fields."""
    Wine = apps.get_model("wine", "Wine")
    Wine.objects.update(drink_from=None, drink_to=None)


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0024_remove_bottle_image_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="drink_from",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Year to start drinking, or 0 for 'now'",
                null=True,
                verbose_name="Drink From",
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="drink_to",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Year to drink by, or 0 for 'now'",
                null=True,
                verbose_name="Drink Until",
            ),
        ),
        migrations.AddIndex(
            model_name="wine",
            index=models.Index(
                fields=["user", "drink_to"], name="wine_user_drinkto_idx"
            ),
        ),
        migrations.RunPython(migrate_drink_by_to_window, reverse_migration),
    ]
