# Generated by Django 5.2.9 on 2026-01-16 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0025_add_drinking_window_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinkrecord",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Star rating (0-3) for this drinking experience.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Rating",
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Default star rating (0-3) for bottles of this wine.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Default Rating",
            ),
        ),
    ]
