# Generated by Django 5.2.9 on 2026-01-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_storageitem_rating"),
        ("wine", "0026_alter_drinkrecord_rating_alter_wine_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkrecord",
            name="storage_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific bottle consumed (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drink_records",
                to="storage.storageitem",
                verbose_name="Bottle",
            ),
        ),
    ]
