# Generated by Django 5.2.9 on 2026-01-21 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0027_add_storage_item_to_drink_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionExtractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "image_count",
                    models.PositiveIntegerField(
                        help_text="Number of images sent for extraction",
                        verbose_name="Image Count",
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(
                        help_text="Raw response from the vision API",
                        verbose_name="Raw Response",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        help_text="Parsed extraction result as JSON",
                        verbose_name="Extracted Data",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        help_text="Confidence level: high, medium, or low",
                        max_length=10,
                        verbose_name="Confidence",
                    ),
                ),
                (
                    "extracted_fields",
                    models.JSONField(
                        help_text="List of fields that were successfully extracted",
                        verbose_name="Extracted Fields",
                    ),
                ),
                (
                    "user_corrections",
                    models.JSONField(
                        blank=True,
                        help_text="Fields that the user corrected after extraction",
                        null=True,
                        verbose_name="User Corrections",
                    ),
                ),
                (
                    "was_successful",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the extraction led to a wine being created",
                        verbose_name="Successful",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        help_text="Any errors during extraction",
                        null=True,
                        verbose_name="Errors",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="claude-haiku-4-5",
                        help_text="AI model used for extraction",
                        max_length=50,
                        verbose_name="Model Used",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken for the extraction in milliseconds",
                        null=True,
                        verbose_name="Processing Time (ms)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wine created from this extraction (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wine.wine",
                        verbose_name="Wine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vision Extraction Log",
                "verbose_name_plural": "Vision Extraction Logs",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["user", "created"], name="visionlog_user_created_idx"
                    ),
                    models.Index(
                        fields=["confidence"], name="visionlog_confidence_idx"
                    ),
                    models.Index(
                        fields=["was_successful"], name="visionlog_success_idx"
                    ),
                ],
            },
        ),
    ]
