# Generated by Django 5.2.9 on 2026-01-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0028_add_vision_extraction_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="wineimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Use this image as the featured thumbnail for the wine.",
                verbose_name="Primary Image",
            ),
        ),
    ]
