# Generated by Django 5.2.9 on 2026-01-30 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0029_add_is_primary_to_wineimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Website URL for this source",
                max_length=500,
                null=True,
                verbose_name="URL",
            ),
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Price"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Recorded At"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_records",
                        to="wine.source",
                        verbose_name="Source",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="wine.wine",
                        verbose_name="Wine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price History Records",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["wine", "source", "recorded_at"],
                        name="pricehistory_wine_source_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "threshold_percent",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Alert when price drops by this percentage or more",
                        verbose_name="Price Drop Threshold (%)",
                    ),
                ),
                (
                    "threshold_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Alert when price drops to or below this amount",
                        max_digits=6,
                        null=True,
                        verbose_name="Target Price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_notified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Notified"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to monitor all sources for this wine",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_alerts",
                        to="wine.source",
                        verbose_name="Source",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to monitor all wines from this source",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_alerts",
                        to="wine.wine",
                        verbose_name="Wine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Alert",
                "verbose_name_plural": "Sale Alerts",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="salealert_user_active_idx"
                    )
                ],
            },
        ),
    ]
