# Generated by Django 5.2.9 on 2026-02-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0032_populate_wine_appellations"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="price_selector",
            field=models.CharField(
                blank=True,
                help_text="CSS selector to extract price, e.g., '.product-price'",
                max_length=200,
                null=True,
                verbose_name="Price CSS Selector",
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="price_url",
            field=models.URLField(
                blank=True,
                help_text="Product page URL for automatic price tracking",
                max_length=500,
                null=True,
                verbose_name="Price URL",
            ),
        ),
    ]
