# Generated by Django 5.2.9 on 2026-02-02 17:40

from django.db import migrations


def populate_household_for_content(apps, schema_editor):
    """
    Populate the household FK on all content models based on the user's
    owner household membership.
    """
    HouseholdMembership = apps.get_model("household", "HouseholdMembership")

    # Build a mapping of user -> household for owners
    owner_households = {}
    for membership in HouseholdMembership.objects.filter(role="OW"):
        owner_households[membership.user_id] = membership.household_id

    # List of models to update (all UserContentModel descendants)
    model_names = [
        ("wine", "Attribute"),
        ("wine", "BottleNote"),
        ("wine", "DrinkingWindowAlert"),
        ("wine", "DrinkRecord"),
        ("wine", "FoodPairing"),
        ("wine", "Grape"),
        ("wine", "PriceHistory"),
        ("wine", "ReorderReminder"),
        ("wine", "SaleAlert"),
        ("wine", "Size"),
        ("wine", "Source"),
        ("wine", "Vineyard"),
        ("wine", "VisionExtractionLog"),
        ("wine", "Wine"),
        ("wine", "Wishlist"),
    ]

    for app_label, model_name in model_names:
        Model = apps.get_model(app_label, model_name)
        for obj in Model.objects.filter(household__isnull=True):
            if obj.user_id and obj.user_id in owner_households:
                obj.household_id = owner_households[obj.user_id]
                obj.save(update_fields=["household"])


def reverse_migration(apps, schema_editor):
    """Reverse: set household to null (not usually recommended)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0034_add_household_to_models"),
        ("household", "0002_populate_existing_users"),
    ]

    operations = [
        migrations.RunPython(
            populate_household_for_content,
            reverse_migration,
        ),
    ]
