# Generated by Django 5.2.9 on 2026-02-06 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0002_populate_existing_users"),
        ("wine", "0035_populate_household_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WineBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100, verbose_name="Barcode")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="wine.wine",
                        verbose_name="Wine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wine Barcode",
                "verbose_name_plural": "Wine Barcodes",
                "indexes": [
                    models.Index(fields=["barcode"], name="winebarcode_barcode_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("barcode", "user"), name="unique_barcode_per_user"
                    )
                ],
            },
        ),
    ]
