# Generated by Django 5.2.9 on 2026-02-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0037_copy_barcodes_to_winebarcode"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="wine",
            name="wine_barcode_idx",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="barcode",
        ),
    ]
