# Generated by Django 6.0.2 on 2026-02-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0039_add_more_appellations"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appellation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="appellation",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_appellation_name_country"
            ),
        ),
    ]
