# Generated by Django 6.0.2 on 2026-02-25 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0043_expand_appellations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="abv",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="ABV",
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Price",
            ),
        ),
    ]
