# Generated by Django 6.0.3 on 2026-03-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0045_collection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["name"],
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
    ]
