# Generated by Django 6.0.3 on 2026-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0047_add_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="external_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Purchase Link"
            ),
        ),
    ]
