# Generated by Django 6.0.3 on 2026-04-30 19:02

from django.db import migrations, models

import wine_cellar.apps.wine.utils


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0047_add_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkrecord",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the bottle, meal, or tasting setting.",
                null=True,
                upload_to=wine_cellar.apps.wine.utils.user_directory_path,
                verbose_name="Photo",
            ),
        ),
    ]
