# Generated by Django 6.0.3 on 2026-05-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0048_wishlist_external_url"),
        ("wine", "0049_drinkrecord_taste_descriptors"),
    ]

    operations = []
