# Generated by Django 6.0.3 on 2026-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0050_merge_20260501_0715"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="ai_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-generated wine summary stored with source citations.",
                verbose_name="AI Summary",
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="ai_summary_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="AI Summary Generated At"
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="ai_summary_model",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="AI Summary Model"
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="ai_summary_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Source list captured for the AI-generated wine summary.",
                verbose_name="AI Summary Sources",
            ),
        ),
    ]
