# Generated by Django 6.0.3 on 2026-10-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0051_wine_ai_summary_wine_ai_summary_generated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visionextractionlog",
            name="model_used",
            field=models.CharField(
                default="claude-haiku-5-5",
                help_text="AI model used for extraction",
                max_length=50,
                verbose_name="Model Used",
            ),
        ),
    ]
