from wine_cellar.conf.settings import (
    ALLOWED_HOSTS,
    AUTH_PASSWORD_VALIDATORS,
    AUTHENTICATION_BACKENDS,
    BASE_DIR,
    CURRENCIES,
    CURRENCY_SYMBOLS,
    DATABASES,
    DEBUG,
    DEFAULT_AUTO_FIELD,
    EMAIL_BACKEND,
    INSTALLED_APPS,
    LANGUAGE_CODE,
    LANGUAGES,
    LOCALE_PATHS,
    LOGIN_REDIRECT_URL,
    LOGOUT_REDIRECT_URL,
    MAP_BASEURL,
    MEDIA_ROOT,
    MEDIA_URL,
    MIDDLEWARE,
    ROOT_DIR,
    ROOT_URLCONF,
    SECRET_KEY,
    SITE_URL,
    STATIC_ROOT,
    STATIC_URL,
    STATICFILES_DIRS,
    TEMPLATES,
    TIME_ZONE,
    USE_I18N,
    USE_TZ,
    VERSION,
    WSGI_APPLICATION,
    ACCOUNT_ADAPTER,
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
