# Generated by Django 5.2.9 on 2025-12-31 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_storageitem_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storage",
            options={"verbose_name": "Storage", "verbose_name_plural": "Storages"},
        ),
        migrations.AlterModelOptions(
            name="storageitem",
            options={
                "verbose_name": "Storage Item",
                "verbose_name_plural": "Storage Items",
            },
        ),
        migrations.AlterField(
            model_name="storage",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="storage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
