# Generated by Django 5.2.9 on 2025-12-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_alter_storage_options_alter_storageitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageitem",
            name="gift_from",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Gift From"
            ),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="is_gift",
            field=models.BooleanField(default=False, verbose_name="Is Gift"),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="occasion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Occasion"
            ),
        ),
    ]
