# Generated by Django 5.2.9 on 2026-01-11 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_storageitem_gift_from_storageitem_is_gift_and_more"),
        ("wine", "0022_add_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="storageitem",
            index=models.Index(
                fields=["user", "deleted"], name="storageitem_user_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storageitem",
            index=models.Index(
                fields=["storage", "row", "column"], name="storageitem_position_idx"
            ),
        ),
    ]
