# Generated by Django 5.2.9 on 2026-01-11 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_add_database_indexes"),
        ("wine", "0023_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="storageitem",
            index=models.Index(
                fields=["wine", "deleted"], name="storageitem_wine_del_idx"
            ),
        ),
    ]
