# Generated by Django 5.2.9 on 2026-01-16 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0008_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageitem",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Star rating (0-3) for this specific bottle.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
