# Generated by Django 5.2.9 on 2026-01-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_storageitem_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="is_cold",
            field=models.BooleanField(default=False, verbose_name="Cold Storage"),
        ),
        migrations.AddField(
            model_name="storage",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Default Storage"),
        ),
        migrations.AddField(
            model_name="storage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
    ]
