# Generated by Django 5.2.9 on 2026-01-22 22:27

from django.db import migrations


def fix_storage_order_values(apps, schema_editor):
    """Set unique sequential order values for each user's storages."""
    Storage = apps.get_model("storage", "Storage")

    # Group storages by user and assign sequential order values
    user_ids = Storage.objects.values_list("user_id", flat=True).distinct()
    for user_id in user_ids:
        storages = Storage.objects.filter(user_id=user_id).order_by("id")
        for index, storage in enumerate(storages):
            storage.order = index
            storage.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_add_is_cold_order_default"),
    ]

    operations = [
        migrations.RunPython(fix_storage_order_values, migrations.RunPython.noop),
    ]
