# Generated by Django 5.2.9 on 2026-02-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0001_create_household_models"),
        ("storage", "0011_fix_storage_order_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="household.household",
                verbose_name="Household",
            ),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="household.household",
                verbose_name="Household",
            ),
        ),
    ]
