# Generated by Django 5.2.9 on 2026-02-02 17:42

from django.db import migrations


def populate_household_for_storage(apps, schema_editor):
    """
    Populate the household FK on Storage and StorageItem models based on the
    user's owner household membership.
    """
    HouseholdMembership = apps.get_model("household", "HouseholdMembership")

    # Build a mapping of user -> household for owners
    owner_households = {}
    for membership in HouseholdMembership.objects.filter(role="OW"):
        owner_households[membership.user_id] = membership.household_id

    # Update Storage
    Storage = apps.get_model("storage", "Storage")
    for obj in Storage.objects.filter(household__isnull=True):
        if obj.user_id and obj.user_id in owner_households:
            obj.household_id = owner_households[obj.user_id]
            obj.save(update_fields=["household"])

    # Update StorageItem
    StorageItem = apps.get_model("storage", "StorageItem")
    for obj in StorageItem.objects.filter(household__isnull=True):
        if obj.user_id and obj.user_id in owner_households:
            obj.household_id = owner_households[obj.user_id]
            obj.save(update_fields=["household"])


def reverse_migration(apps, schema_editor):
    """Reverse: set household to null (not usually recommended)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0012_add_household_to_storage"),
        ("household", "0002_populate_existing_users"),
    ]

    operations = [
        migrations.RunPython(
            populate_household_for_storage,
            reverse_migration,
        ),
    ]
