# Generated by Django 5.2.9 on 2026-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_populate_household_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="app_type",
            field=models.CharField(default="wine", max_length=10),
        ),
    ]
