# Generated by Django 5.2.9 on 2026-02-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0014_storage_app_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="cell_mask",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
