# Generated by Django 6.0.2 on 2026-02-25 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0015_storage_cell_mask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
