# Generated by Django 6.0.3 on 2026-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0017_bottle_history_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageitem",
            name="given_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Given"),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="given_occasion",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Given Occasion"
            ),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="recipient",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Recipient"
            ),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="removal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consumed", "Consumed"),
                    ("given", "Given Away"),
                    ("removed", "Removed"),
                ],
                default="",
                max_length=20,
                verbose_name="Removal Reason",
            ),
        ),
    ]
