# Generated by Django 6.0.3 on 2026-08-10 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0003_remove_householdsettings_language"),
        ("storage", "0018_storageitem_given_date_storageitem_given_occasion_and_more"),
        ("wine", "0051_wine_ai_summary_wine_ai_summary_generated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storageitem",
            name="occasion_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the occasion this bottle is reserved for.",
                null=True,
                verbose_name="Occasion Date",
            ),
        ),
        migrations.AddIndex(
            model_name="storageitem",
            index=models.Index(
                fields=["household", "deleted", "occasion_date"],
                name="storitem_hh_del_occas_idx",
            ),
        ),
    ]
