# Generated by Django 6.0.7 on 2026-08-13 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("household", "0003_remove_householdsettings_language"),
        ("storage", "0019_storageitem_occasion_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("storage_item_id", models.PositiveIntegerField()),
                ("target_row", models.PositiveIntegerField()),
                ("target_column", models.PositiveIntegerField()),
                ("app_type", models.CharField(default="wine", max_length=10)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "storage_item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_moves",
                        to="storage.storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planned Move",
                "verbose_name_plural": "Planned Moves",
                "indexes": [
                    models.Index(
                        fields=[
                            "household",
                            "app_type",
                            "target_storage",
                            "target_row",
                            "target_column",
                        ],
                        name="planmove_target_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("storage_item_type", "storage_item_id"),
                        name="plannedmove_storage_item_unique",
                    )
                ],
            },
        ),
    ]
