# Generated by Django 5.2.9 on 2025-12-31 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_usersettings_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersettings",
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "Dollar"), ("GBP", "Pound Sterling")],
                default="EUR",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[("de-de", "German"), ("en-gb", "British English")],
                default="en-gb",
                max_length=7,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="notifications",
            field=models.BooleanField(default=True, verbose_name="Notifications"),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
