# Generated by Django 5.2.9 on 2026-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_usersettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[("en-gb", "British English")],
                default="en-gb",
                max_length=7,
                verbose_name="Language",
            ),
        ),
    ]
