# Generated by Django 5.2.9 on 2026-02-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0001_create_household_models"),
        ("user", "0005_alter_usersettings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="active_household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_users",
                to="household.household",
                verbose_name="Active Household",
            ),
        ),
    ]
