# Generated by Django 6.0.2 on 2026-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_add_active_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="reminder_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Receive reminders when wines approach their drink-by date",
                verbose_name="Drink Window Reminders",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="reminder_years_before",
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "How many years before the drink-by date"
                    " to start reminding (0 = in the year itself)"
                ),
                verbose_name="Years Before Drink-By",
            ),
        ),
    ]
