# Generated by Django 6.0.3 on 2026-03-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_push_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="language",
        ),
    ]
