# Generated by Django 5.2.9 on 2026-02-11 00:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import wine_cellar.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("household", "0002_populate_existing_users"),
        ("storage", "0013_populate_household_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bottler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, default="", max_length=50)),
                ("country", models.CharField(default="GB", max_length=2)),
                ("website", models.URLField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("is_user_created", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Distillery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(default="GB", max_length=2)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("SI", "Silent"),
                            ("CL", "Closed"),
                            ("DE", "Demolished"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("closed_year", models.PositiveIntegerField(blank=True, null=True)),
                ("owner", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_user_created", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "distilleries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Attribute")),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="Whisky",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "whisky_type",
                    models.CharField(
                        choices=[
                            ("SM", "Single Malt"),
                            ("BM", "Blended Malt"),
                            ("BL", "Blended"),
                            ("SG", "Single Grain"),
                        ],
                        default="SM",
                        max_length=2,
                        verbose_name="Type",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="GB", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "age_statement",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for NAS (No Age Statement).",
                        null=True,
                        verbose_name="Age Statement",
                    ),
                ),
                (
                    "vintage_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Distilled Year"
                    ),
                ),
                (
                    "bottled_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Bottled Year"
                    ),
                ),
                (
                    "abv",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="ABV %",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("0.05", "Miniature (50ml)"),
                            ("0.10", "Sample (100ml)"),
                            ("0.35", "Half Bottle (350ml)"),
                            ("0.70", "Standard (700ml)"),
                            ("1.00", "Litre (1000ml)"),
                            ("1.50", "Magnum (1500ml)"),
                            ("0.00", "Other"),
                        ],
                        default="0.70",
                        max_length=4,
                        verbose_name="Bottle Size",
                    ),
                ),
                (
                    "peated_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UP", "Unpeated"),
                            ("LP", "Lightly Peated"),
                            ("PE", "Peated"),
                            ("HP", "Heavily Peated"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Peated Level",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Color"
                    ),
                ),
                (
                    "bottler_series",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Bottler Series",
                    ),
                ),
                (
                    "cask_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Cask Number",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Batch Number",
                    ),
                ),
                (
                    "bottle_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 123/500",
                        max_length=100,
                        verbose_name="Bottle Number",
                    ),
                ),
                (
                    "limited_edition",
                    models.BooleanField(default=False, verbose_name="Limited Edition"),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Release Year"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "rrp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="RRP",
                    ),
                ),
                (
                    "drink_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Drink From Year"
                    ),
                ),
                (
                    "drink_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Drink To Year"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Comment"),
                ),
                (
                    "bottler",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for Official Bottling (OB).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.bottler",
                        verbose_name="Bottler",
                    ),
                ),
                (
                    "distillery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.distillery",
                        verbose_name="Distillery",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "attributes",
                    models.ManyToManyField(
                        blank=True,
                        to="whisky.whiskyattribute",
                        verbose_name="Attributes",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "whiskies",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyDrinkingWindowAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("alert_date", models.DateField(verbose_name="Alert Date")),
                ("message", models.CharField(max_length=200, verbose_name="Message")),
                ("is_read", models.BooleanField(default=False)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="whisky.whisky"
                    ),
                ),
            ],
            options={
                "ordering": ["-alert_date"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=wine_cellar.apps.core.models.user_directory_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=wine_cellar.apps.core.models.user_directory_path,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[("LF", "Front Label"), ("LB", "Back Label")],
                        default="LF",
                        max_length=2,
                        verbose_name="Image Type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Image"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="whisky.whisky",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("country", models.CharField(default="GB", max_length=2)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("name", "country")},
            },
        ),
        migrations.AddField(
            model_name="whisky",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="whisky.whiskyregion",
                verbose_name="Region",
            ),
        ),
        migrations.AddField(
            model_name="distillery",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="distilleries",
                to="whisky.whiskyregion",
            ),
        ),
        migrations.CreateModel(
            name="WhiskyReorderReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Minimum Stock"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="whisky.whisky"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WhiskySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Source")),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WhiskySaleAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "threshold_percent",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Discount Threshold %"
                    ),
                ),
                (
                    "threshold_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Target Price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_notified", models.DateTimeField(blank=True, null=True)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="whisky.whisky"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.whiskysource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="whisky.whisky"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.whiskysource",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "price histories",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyStorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("row", models.PositiveIntegerField(blank=True, null=True)),
                ("column", models.PositiveIntegerField(blank=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_gift", models.BooleanField(default=False, verbose_name="Is Gift")),
                (
                    "gift_from",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gift From"
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Occasion"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "fill_level",
                    models.CharField(
                        choices=[
                            ("FU", "Full (sealed)"),
                            ("3Q", "3/4"),
                            ("HA", "Half"),
                            ("1Q", "1/4"),
                            ("NE", "Nearly Empty"),
                            ("EM", "Empty"),
                        ],
                        default="FU",
                        max_length=2,
                        verbose_name="Fill Level",
                    ),
                ),
                (
                    "opened_date",
                    models.DateField(blank=True, null=True, verbose_name="Date Opened"),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whisky_items",
                        to="storage.storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="whisky.whisky"
                    ),
                ),
            ],
            options={
                "verbose_name": "Whisky Bottle",
                "verbose_name_plural": "Whisky Bottles",
            },
        ),
        migrations.CreateModel(
            name="WhiskyDrinkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("date_consumed", models.DateField(verbose_name="Date")),
                (
                    "tasting_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Tasting Notes"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "shared_with",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Shared With",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Occasion"
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="whisky.whisky"
                    ),
                ),
                (
                    "storage_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.whiskystorageitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_consumed"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyBottleNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("note_date", models.DateField(verbose_name="Date")),
                ("note", models.TextField(verbose_name="Note")),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "storage_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="whisky.whiskystorageitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-note_date"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyVisionExtractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("image_count", models.PositiveIntegerField(default=0)),
                ("raw_response", models.TextField(blank=True, default="")),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("confidence", models.CharField(blank=True, default="", max_length=20)),
                ("extracted_fields", models.JSONField(blank=True, default=list)),
                ("user_corrections", models.JSONField(blank=True, default=dict)),
                ("was_successful", models.BooleanField(default=False)),
                ("errors", models.TextField(blank=True, default="")),
                (
                    "model_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.whisky",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="WhiskyWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "whisky_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SM", "Single Malt"),
                            ("BM", "Blended Malt"),
                            ("BL", "Blended"),
                            ("SG", "Single Grain"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "age_statement",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Age"
                    ),
                ),
                (
                    "price_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Max Price",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                (
                    "purchased",
                    models.BooleanField(default=False, verbose_name="Purchased"),
                ),
                (
                    "distillery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.distillery",
                        verbose_name="Distillery",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whisky.whiskyregion",
                        verbose_name="Region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="CaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="1 = primary cask, 2+ = subsequent casks/finishes",
                        verbose_name="Maturation Order",
                    ),
                ),
                (
                    "cask_type",
                    models.CharField(
                        choices=[
                            ("BR", "Barrel (190L)"),
                            ("HH", "Hogshead (250L)"),
                            ("BU", "Butt (500L)"),
                            ("PU", "Puncheon (500L)"),
                            ("QC", "Quarter Cask (125L)"),
                            ("PI", "Pipe (650L)"),
                            ("OC", "Octave (50L)"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        verbose_name="Cask Type",
                    ),
                ),
                (
                    "wood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AO", "American Oak"),
                            ("EO", "European Oak"),
                            ("JM", "Japanese Mizunara"),
                            ("FO", "French Oak"),
                            ("OT", "Other"),
                        ],
                        default="",
                        max_length=2,
                        verbose_name="Wood Type",
                    ),
                ),
                (
                    "previous_contents",
                    models.CharField(
                        choices=[
                            ("BO", "Bourbon"),
                            ("SO", "Sherry (Oloroso)"),
                            ("SP", "Sherry (Pedro Ximénez)"),
                            ("SF", "Sherry (Fino)"),
                            ("PO", "Port"),
                            ("RU", "Rum"),
                            ("WR", "Wine (Red)"),
                            ("WW", "Wine (White)"),
                            ("MA", "Madeira"),
                            ("MS", "Marsala"),
                            ("VO", "Virgin Oak"),
                            ("BE", "Beer / Ale"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        verbose_name="Previous Contents",
                    ),
                ),
                (
                    "duration_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (years)"
                    ),
                ),
                (
                    "is_finish",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is a finishing cask "
                        "rather than primary maturation.",
                        verbose_name="Finish",
                    ),
                ),
                (
                    "cask_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Cask Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cask_history",
                        to="whisky.whisky",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cask histories",
                "ordering": ["whisky", "order"],
                "unique_together": {("whisky", "order")},
            },
        ),
        migrations.CreateModel(
            name="WhiskyBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(db_index=True, max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whisky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="whisky.whisky",
                    ),
                ),
            ],
            options={
                "unique_together": {("barcode", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="whisky",
            index=models.Index(
                fields=["user", "whisky_type"], name="whisky_user_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whisky",
            index=models.Index(
                fields=["user", "created"], name="whisky_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whisky",
            index=models.Index(
                fields=["distillery", "age_statement"], name="whisky_dist_age_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whisky",
            index=models.Index(fields=["name"], name="whisky_name_idx"),
        ),
        migrations.AddIndex(
            model_name="whisky",
            index=models.Index(fields=["country"], name="whisky_country_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="whisky",
            unique_together={
                (
                    "name",
                    "whisky_type",
                    "abv",
                    "size",
                    "vintage_year",
                    "bottled_year",
                    "user",
                )
            },
        ),
        migrations.AddIndex(
            model_name="distillery",
            index=models.Index(
                fields=["region", "status"], name="distillery_region_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="distillery",
            unique_together={("name", "country")},
        ),
        migrations.AlterUniqueTogether(
            name="whiskyreorderreminder",
            unique_together={("whisky", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="whiskysource",
            unique_together={("name", "user")},
        ),
        migrations.AddIndex(
            model_name="whiskystorageitem",
            index=models.Index(fields=["user", "deleted"], name="wsi_user_del_idx"),
        ),
        migrations.AddIndex(
            model_name="whiskystorageitem",
            index=models.Index(
                fields=["storage", "row", "column"], name="wsi_position_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whiskystorageitem",
            index=models.Index(fields=["whisky", "deleted"], name="wsi_whisky_del_idx"),
        ),
        migrations.AddIndex(
            model_name="whiskydrinkrecord",
            index=models.Index(
                fields=["user", "date_consumed"], name="wdr_user_date_idx"
            ),
        ),
    ]
