# Generated by Django 5.2.9 on 2026-02-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whisky",
            name="cask_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Barrel (190L)"),
                    ("HH", "Hogshead (250L)"),
                    ("BU", "Butt (500L)"),
                    ("PU", "Puncheon (500L)"),
                    ("QC", "Quarter Cask (125L)"),
                    ("PI", "Pipe (650L)"),
                    ("OC", "Octave (50L)"),
                    ("OT", "Other"),
                ],
                max_length=2,
                null=True,
                verbose_name="Cask Type",
            ),
        ),
        migrations.AlterField(
            model_name="whisky",
            name="peated_level",
            field=models.CharField(
                blank=True,
                choices=[("UP", "Unpeated"), ("PE", "Peated")],
                max_length=2,
                null=True,
                verbose_name="Peated",
            ),
        ),
    ]
