# Generated by Django 5.2.9 on 2026-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0002_whisky_cask_type_alter_whisky_peated_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caskhistory",
            name="cask_type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Cask Type"
            ),
        ),
        migrations.AlterField(
            model_name="whisky",
            name="cask_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Ex-Bourbon, Ex-Sherry (Oloroso), Virgin Oak",
                max_length=100,
                verbose_name="Cask Type",
            ),
        ),
    ]
