# Generated by Django 5.2.9 on 2026-02-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0003_cask_type_free_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whisky",
            name="country",
            field=models.CharField(default="XS", max_length=2, verbose_name="Country"),
        ),
    ]
