# Generated by Django 5.2.9 on 2026-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0005_fill_level_owner_source_dreg"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiskystorageitem",
            name="owner",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Owner"
            ),
        ),
        migrations.AlterField(
            model_name="whisky",
            name="cask_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Bourbon, Sherry (Oloroso), Virgin Oak",
                max_length=100,
                verbose_name="Cask Type",
            ),
        ),
    ]
