# Generated by Django 5.2.9 on 2026-02-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0006_storage_item_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whisky",
            name="drink_from",
        ),
        migrations.RemoveField(
            model_name="whisky",
            name="drink_to",
        ),
    ]
