# Generated by Django 5.2.9 on 2026-02-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0007_remove_drinking_window_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whisky",
            name="size",
            field=models.CharField(
                choices=[
                    ("0.05", "Miniature (50ml)"),
                    ("0.10", "Sample (100ml)"),
                    ("0.20", "Small (200ml)"),
                    ("0.35", "Half Bottle (350ml)"),
                    ("0.50", "Half Litre (500ml)"),
                    ("0.70", "Standard (700ml)"),
                    ("1.00", "Litre (1000ml)"),
                    ("1.50", "Magnum (1500ml)"),
                    ("0.00", "Other"),
                ],
                default="0.70",
                max_length=4,
                verbose_name="Bottle Size",
            ),
        ),
    ]
