# Generated by Django 6.0.2 on 2026-02-16 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0002_populate_existing_users"),
        ("whisky", "0008_add_bottle_sizes_200ml_500ml"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="caskhistory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="distillery",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="whisky",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="whiskyattribute",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="whiskybarcode",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="whiskyregion",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="whiskyreorderreminder",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="whiskysource",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="caskhistory",
            constraint=models.UniqueConstraint(
                fields=("whisky", "order"), name="unique_caskhistory_whisky_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="distillery",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_distillery_name_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="whisky",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "whisky_type",
                    "abv",
                    "size",
                    "vintage_year",
                    "bottled_year",
                    "user",
                ),
                name="unique_whisky_natural_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="whiskyattribute",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_whiskyattribute_name_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="whiskybarcode",
            constraint=models.UniqueConstraint(
                fields=("barcode", "user"), name="unique_whiskybarcode_barcode_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="whiskyregion",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_whiskyregion_name_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="whiskyreorderreminder",
            constraint=models.UniqueConstraint(
                fields=("whisky", "user"),
                name="unique_whiskyreorderreminder_whisky_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="whiskysource",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_whiskysource_name_user"
            ),
        ),
    ]
