# Generated by Django 6.0.2 on 2026-02-25 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0011_remove_whisky_rrp_preserve_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whisky",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="whiskystorageitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
