# Generated by Django 6.0.2 on 2026-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0011_remove_whisky_rrp_preserve_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="whisky",
            name="cask_strength",
            field=models.BooleanField(default=False, verbose_name="Cask Strength"),
        ),
    ]
