# Generated by Django 6.0.2 on 2026-02-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0012_alter_whisky_price_alter_whiskystorageitem_price"),
        ("whisky", "0012_whisky_cask_strength"),
    ]

    operations = []
