# Generated by Django 6.0.3 on 2026-03-08 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0002_populate_existing_users"),
        ("whisky", "0013_merge_20260225_1257"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        verbose_name="Description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Color"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Icon"
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whisky_collection_items",
                        to="household.household",
                        verbose_name="Household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whisky_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "whiskies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collections",
                        to="whisky.whisky",
                        verbose_name="Whiskies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "household"),
                        name="unique_whisky_collection_name_per_household",
                    )
                ],
            },
        ),
    ]
