# Generated by Django 6.0.3 on 2026-03-09 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0002_populate_existing_users"),
        ("whisky", "0014_collection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="whisky",
            name="unique_whisky_natural_key",
        ),
        migrations.AddField(
            model_name="whisky",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name="whisky",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "whisky_type",
                    "abv",
                    "size",
                    "vintage_year",
                    "bottled_year",
                    "user",
                ),
                condition=models.Q(deleted=False),
                name="unique_whisky_natural_key",
            ),
        ),
    ]
