# Generated by Django 6.0.3 on 2026-03-24 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0017_bottle_history_tracking"),
        ("whisky", "0015_add_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="whiskystorageitem",
            name="finished_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Finished"),
        ),
        migrations.CreateModel(
            name="WhiskyBottleMoveHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_row", models.PositiveIntegerField(blank=True, null=True)),
                ("from_column", models.PositiveIntegerField(blank=True, null=True)),
                ("to_row", models.PositiveIntegerField(blank=True, null=True)),
                ("to_column", models.PositiveIntegerField(blank=True, null=True)),
                ("moved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="storage.storage",
                        verbose_name="From Storage",
                    ),
                ),
                (
                    "storage_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_history",
                        to="whisky.whiskystorageitem",
                    ),
                ),
                (
                    "to_storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="storage.storage",
                        verbose_name="To Storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whisky Bottle Move History",
                "verbose_name_plural": "Whisky Bottle Move Histories",
                "ordering": ["moved_at"],
            },
        ),
    ]
