# Generated by Django 6.0.3 on 2026-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0017_whiskystorageitem_given_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiskywishlist",
            name="external_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Purchase Link"
            ),
        ),
    ]
