# Generated by Django 6.0.3 on 2026-04-30 19:02

from django.db import migrations, models

import wine_cellar.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0017_whiskystorageitem_given_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiskydrinkrecord",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the bottle, meal, or tasting setting.",
                null=True,
                upload_to=wine_cellar.apps.core.models.user_directory_path,
                verbose_name="Photo",
            ),
        ),
    ]
