# Generated by Django 6.0.3 on 2026-04-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0018_whiskydrinkrecord_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiskydrinkrecord",
            name="taste_descriptors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected flavor descriptors from the tasting wheel.",
                verbose_name="Taste Descriptors",
            ),
        ),
    ]
