# Generated by Django 6.0.3 on 2026-05-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whisky", "0018_whiskywishlist_external_url"),
        ("whisky", "0019_whiskydrinkrecord_taste_descriptors"),
    ]

    operations = []
