# Generated by Django 6.0.8 on 2026-09-16 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0003_remove_householdsettings_language"),
        ("storage", "0020_plannedmove"),
        ("whisky", "0020_merge_20260501_0715"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="whiskystorageitem",
            name="miniature_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The handwritten number on this miniature.",
                null=True,
                verbose_name="Miniature Label Number",
            ),
        ),
        migrations.AddConstraint(
            model_name="whiskystorageitem",
            constraint=models.UniqueConstraint(
                fields=("household", "miniature_number"),
                name="unique_whisky_miniature_label",
            ),
        ),
    ]
